import type { Metadata } from "next";
import Link from "next/link";
import { requireDriver } from "@/lib/driver-session";
import { SUPPORT_EMAIL, SUPPORT_PHONE_DISPLAY, SUPPORT_PHONE_E164 } from "@/lib/site";
import Icon from "../../components/driver/Icon";
import styles from "../../components/driver/driver.module.css";
export const metadata: Metadata = { title: "Driver support", description: "Contact AutoRescue about your account or a roadside request.", alternates: { canonical: "/profile/support" } };
export default async function SupportPage() {
  await requireDriver();
  return <><header className={styles.pageHeading}><div><h1>Help and support</h1><p>Get help with a request, your vehicle or your account.</p></div></header><div className={styles.twoColumns}><section className={styles.panel}><div className={styles.panelBody}><Icon name="support" size={34} /><h2 className="mt-4">Speak with AutoRescue</h2><p className={styles.muted}>Have your location, vehicle details and request reference ready.</p><a className={styles.supportNumber} href={"tel:" + SUPPORT_PHONE_E164}>{SUPPORT_PHONE_DISPLAY}</a><a className={styles.textLink + " " + styles.wrap} href={"mailto:" + SUPPORT_EMAIL}>{SUPPORT_EMAIL}</a></div><div className={styles.supportList}><a href={"https://wa.me/" + SUPPORT_PHONE_E164.replace(/\D/g, "")} target="_blank" rel="noopener noreferrer">Open WhatsApp <Icon name="arrow" size={17} /></a><Link href="/contact">Send an inquiry <Icon name="arrow" size={17} /></Link><Link href="/profile/requests">Find a request reference <Icon name="arrow" size={17} /></Link><Link href="/case-studies">Read the roadside guide <Icon name="arrow" size={17} /></Link></div></section><section className={styles.panel + " " + styles.panelBody}><h2>Common questions</h2><div className={styles.faq}><details><summary>What happens after I submit a request?</summary><p>Your details are saved in your account. Call support to confirm service availability, cost and arrival arrangements. A submitted request is not confirmation that a mechanic has been dispatched.</p></details><details><summary>Can I change or cancel my request?</summary><p>Contact support and quote your request reference. Saved requests cannot currently be edited from your account.</p></details><details><summary>Where do I see updates?</summary><p>Open the request from Your requests and select Refresh. Only confirmed status updates are shown; live mechanic tracking is not currently available.</p></details><details><summary>How do I change my password?</summary><p>Use the reset-password link in Account settings. A recovery link will be sent to your account email.</p><Link className={styles.textLink} href="/forgot-password">Reset password</Link></details></div></section></div></>;
}
